version: '3'
volumes:
  data:
services:
  backend-db:
    container_name: backend-db
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: ryelne
      MARIADB_USER: ryelne
      MARIADB_PASSWORD: ryelne
    volumes:
      - data:/var/lib/mariadb
    ports:
      - "3306:3306"
    networks:
      - backend
  backend-api:
    container_name: backend-api
    build: ./
    environment:
      spring.datasource.url: jdbc:mariadb://backend-db:3306/ryelne
      spring.datasource.driver-class-name: org.mariadb.jdbc.Driver
      spring.datasource.username: ryelne
      spring.datasource.password: ryelne
    ports:
      - "8080:8080"
    depends_on:
      - backend-db
    networks:
      - backend
networks:
  backend: